# Site Info
title:              "Amos Navarre Hebb"
description:        "Amos' website complete with a stale blog"
author_name:        "Amos Hebb" # change this to your name
logo_url:           ~/assets/mugsquare.jpg
#logo_url:           https://avatars3.githubusercontent.com/u/10426715?v=4 # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://www.amoshebb.com # main url
# baseurl:           put this back if you want all pages to have something
permalink:          /:categories/:year/:month/:day/:title:output_ext # Post permalink
timezone:           America/Toronto # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
